[package]
name = "alluka_rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "_alluka"
crate-type = ["cdylib"]

[dependencies]
async-oneshot = "0.5.0"

[dependencies.tokio]
features = ["rt-multi-thread"]
version = "1.19.2"

[dependencies.pyo3]
features = ["extension-module"]
version = "0.16.5"

[profile.release]
codegen-units = 1
lto = true
strip = true
