[package]
name = "alluka_rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "_alluka"
crate-type = ["cdylib"]

[dependencies]
async-executor = "1.4.1"
async-oneshot = "0.5.0"
async-recursion = "1.0.0"
futures = "0.3.21"

[dependencies.pyo3]
features = ["extension-module"]
version = "0.16.5"

[profile.release]
codegen-units = 1
lto = true
strip = true
